package application.minigame.evenodd.interfaces;

/**
 * An interface for EOModel.
 */
public interface EOModel {

    /**
     * If the value passed to me by the Controller is 2 (the player has chosen even) and the
     * value generated by Random is even then the player has WON. If the value
     * passed to me by the Controller is 1 (the player has chosen odd) and the value
     * generated by Random is odd then the player has WON. In the other case
     * lost. I pass the value to the view that will print it on the screen.
     *
     * @param value from contoller. 1 odd, 2 even
     */
    void checkWin(final int value);
}
