/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.goosegame;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application{

	@Override
	public void start(Stage primaryStage) throws Exception {
		Label l = new Label("Hello, JavaFX!");
		Scene scene = new Scene(new StackPane(l), 640, 480);
		primaryStage.setScene(scene);
		primaryStage.show();
		primaryStage.setTitle("Goose Game");
		
	}
	
	public static void main(String[] args) {
        launch();
    }
}
